export type UserRoleCode = 
  | 'ADMIN'
  | 'DOCTOR'
  | 'NURSE'
  | 'RECEPTIONIST'
  | 'LAB_STAFF'
  | 'PHARMACIST'
  | 'ACCOUNTANT';

export const USER_ROLES: Record<UserRoleCode, UserRoleCode> = {
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  NURSE: 'NURSE',
  RECEPTIONIST: 'RECEPTIONIST',
  LAB_STAFF: 'LAB_STAFF',
  PHARMACIST: 'PHARMACIST',
  ACCOUNTANT: 'ACCOUNTANT'
};

export const PERMISSIONS = {
  // Patient Permissions
  PATIENT_READ: 'PATIENT_READ',
  PATIENT_CREATE: 'PATIENT_CREATE',
  PATIENT_UPDATE: 'PATIENT_UPDATE',
  PATIENT_DELETE: 'PATIENT_DELETE',

  // Doctor Permissions
  DOCTOR_READ: 'DOCTOR_READ',
  DOCTOR_CREATE: 'DOCTOR_CREATE',
  DOCTOR_UPDATE: 'DOCTOR_UPDATE',
  DOCTOR_DELETE: 'DOCTOR_DELETE',

  // Appointment Permissions
  APPOINTMENT_READ: 'APPOINTMENT_READ',
  APPOINTMENT_CREATE: 'APPOINTMENT_CREATE',
  APPOINTMENT_UPDATE: 'APPOINTMENT_UPDATE',
  APPOINTMENT_CANCEL: 'APPOINTMENT_CANCEL',

  // Medical Records Permissions
  MEDICAL_RECORD_READ: 'MEDICAL_RECORD_READ',
  MEDICAL_RECORD_CREATE: 'MEDICAL_RECORD_CREATE',
  MEDICAL_RECORD_UPDATE: 'MEDICAL_RECORD_UPDATE',

  // Laboratory Permissions
  LAB_READ: 'LAB_READ',
  LAB_CREATE: 'LAB_CREATE',
  LAB_UPDATE: 'LAB_UPDATE',
  LAB_RESULT_ENTRY: 'LAB_RESULT_ENTRY',

  // Pharmacy Permissions
  PHARMACY_READ: 'PHARMACY_READ',
  PHARMACY_CREATE: 'PHARMACY_CREATE',
  PHARMACY_UPDATE: 'PHARMACY_UPDATE',
  PHARMACY_DISPENSE: 'PHARMACY_DISPENSE',

  // Billing & Payments
  BILLING_READ: 'BILLING_READ',
  BILLING_CREATE: 'BILLING_CREATE',
  PAYMENT_READ: 'PAYMENT_READ',
  PAYMENT_CREATE: 'PAYMENT_CREATE',

  // Admissions & Wards
  ADMISSION_READ: 'ADMISSION_READ',
  ADMISSION_CREATE: 'ADMISSION_CREATE',
  ADMISSION_UPDATE: 'ADMISSION_UPDATE',

  // Outpatients
  OUTPATIENT_READ: 'OUTPATIENT_READ',
  OUTPATIENT_MANAGE: 'OUTPATIENT_MANAGE',

  // Staff & HR
  STAFF_READ: 'STAFF_READ',
  STAFF_CREATE: 'STAFF_CREATE',
  STAFF_UPDATE: 'STAFF_UPDATE',

  // Reports
  REPORT_READ: 'REPORT_READ',

  // Administration & System
  USER_MANAGE: 'USER_MANAGE',
  AUDIT_READ: 'AUDIT_READ',
  SETTINGS_MANAGE: 'SETTINGS_MANAGE'
} as const;

export type PermissionCode = keyof typeof PERMISSIONS;

export const ROLE_DEFAULT_PERMISSIONS: Record<UserRoleCode, string[]> = {
  ADMIN: Object.values(PERMISSIONS),
  DOCTOR: [
    PERMISSIONS.PATIENT_READ, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.DOCTOR_READ,
    PERMISSIONS.APPOINTMENT_READ, PERMISSIONS.APPOINTMENT_CREATE, PERMISSIONS.APPOINTMENT_UPDATE, PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.MEDICAL_RECORD_READ, PERMISSIONS.MEDICAL_RECORD_CREATE, PERMISSIONS.MEDICAL_RECORD_UPDATE,
    PERMISSIONS.LAB_READ, PERMISSIONS.LAB_CREATE,
    PERMISSIONS.PHARMACY_READ,
    PERMISSIONS.ADMISSION_READ,
    PERMISSIONS.OUTPATIENT_READ, PERMISSIONS.OUTPATIENT_MANAGE,
    PERMISSIONS.REPORT_READ
  ],
  NURSE: [
    PERMISSIONS.PATIENT_READ, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.DOCTOR_READ,
    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.MEDICAL_RECORD_READ, PERMISSIONS.MEDICAL_RECORD_UPDATE,
    PERMISSIONS.LAB_READ,
    PERMISSIONS.ADMISSION_READ, PERMISSIONS.ADMISSION_CREATE, PERMISSIONS.ADMISSION_UPDATE,
    PERMISSIONS.OUTPATIENT_READ, PERMISSIONS.OUTPATIENT_MANAGE
  ],
  RECEPTIONIST: [
    PERMISSIONS.PATIENT_READ, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_UPDATE,
    PERMISSIONS.DOCTOR_READ,
    PERMISSIONS.APPOINTMENT_READ, PERMISSIONS.APPOINTMENT_CREATE, PERMISSIONS.APPOINTMENT_UPDATE, PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.BILLING_READ, PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.PAYMENT_READ, PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.ADMISSION_READ,
    PERMISSIONS.OUTPATIENT_READ, PERMISSIONS.OUTPATIENT_MANAGE
  ],
  LAB_STAFF: [
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.DOCTOR_READ,
    PERMISSIONS.LAB_READ, PERMISSIONS.LAB_CREATE, PERMISSIONS.LAB_UPDATE, PERMISSIONS.LAB_RESULT_ENTRY
  ],
  PHARMACIST: [
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.DOCTOR_READ,
    PERMISSIONS.PHARMACY_READ, PERMISSIONS.PHARMACY_CREATE, PERMISSIONS.PHARMACY_UPDATE, PERMISSIONS.PHARMACY_DISPENSE,
    PERMISSIONS.BILLING_READ
  ],
  ACCOUNTANT: [
    PERMISSIONS.PATIENT_READ,
    PERMISSIONS.BILLING_READ, PERMISSIONS.BILLING_CREATE,
    PERMISSIONS.PAYMENT_READ, PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.REPORT_READ
  ]
};
